package com.example.myquran.entities.list;

import com.example.myquran.entities.model.SurahModel;

import java.util.ArrayList;

public class SurahList {
    private ArrayList<SurahModel> surahList=new ArrayList<>();

    public ArrayList<SurahModel> getSurahList() {
       surahList.add(new SurahModel(1, "الفاتحة", "Al-Fatiha (The Opening)", 1));
       surahList.add(new SurahModel(2, "البقرة", "Al-Baqarah (The Cow)", 2));
       surahList.add(new SurahModel(3, "آل عمران", "Al-'Imran (The Family of Imran)", 50));
       surahList.add(new SurahModel(4, "النساء", "An-Nisa' (The Women)", 77));
       surahList.add(new SurahModel(5, "المائدة", "Al-Ma'idah (The Table spread with Food)", 106));
       surahList.add(new SurahModel(6, "الأنعام", "Al-An'am (The Cattle)", 128));
       surahList.add(new SurahModel(7, "الأعراف", "Al-A'raf (The Heights)", 151));
       surahList.add(new SurahModel(8, "الأنفال", "Al-Anfal (The Spoils of War)", 177));
       surahList.add(new SurahModel(9, "التوبة", "At-Taubah (The Repentance)", 187));
       surahList.add(new SurahModel(10, "يونس", "Yunus (Jonah)", 208));
       surahList.add(new SurahModel(11, "هود", "Hud (Hud)", 222));
       surahList.add(new SurahModel(12, "يوسف", "Yusuf (Joseph)", 236));
       surahList.add(new SurahModel(13, "الرعد", "Ar-Ra'd (The Thunder)", 249));
       surahList.add(new SurahModel(14, "ابراهيم", "Ibrahim (Abraham)", 256));
       surahList.add(new SurahModel(15, "الحجر", "Al-Hijr (The Rocky Tract)", 262));
       surahList.add(new SurahModel(16, "النحل", "An-Nahl (The Bees)", 268));
       surahList.add(new SurahModel(17, "الإسراء", " Al-Isra' (The Journey by Night)", 282));
       surahList.add(new SurahModel(18, "الكهف", "Al-Kahf (The Cave)", 294));
       surahList.add(new SurahModel(19, "مريم", "Maryam (Mary)", 305));
       surahList.add(new SurahModel(20, "طه", "Ta-Ha (Ta-Ha)", 313));
       surahList.add(new SurahModel(21, "الأنبياء", "Al-Anbiya' (The Prophets)", 322));
       surahList.add(new SurahModel(22, "الحج", "Al-Hajj (The Pilgrimage)", 332));
       surahList.add(new SurahModel(23, "المؤمنون", "Al-Mu'minun (The Believers)", 342));
       surahList.add(new SurahModel(24, "النور", "An-Nur (The Light)", 350));
       surahList.add(new SurahModel(25, "الفرقان", "Al-Furqan (The Criterion)", 360));
       surahList.add(new SurahModel(26, "الشعراء", "Ash-Shu'ara' (The Poets)", 367));
       surahList.add(new SurahModel(27, "النمل", "An-Naml (The Ants)", 377));
       surahList.add(new SurahModel(28, "القصص", "Al-Qasas (The Narration)", 386));
       surahList.add(new SurahModel(29, "العنكبوت", "Al-'Ankabut (The Spider)", 397));
       surahList.add(new SurahModel(30, "الروم", "Ar-Rum (The Romans)", 405));
       surahList.add(new SurahModel(31, "لقمان", "Luqman (Luqman)", 411));
       surahList.add(new SurahModel(32, "السجدة", "As-Sajdah (The Prostration)", 415));
       surahList.add(new SurahModel(33, "الأحزاب", "Al-Ahzab (The Confederates)", 418));
       surahList.add(new SurahModel(34, "سبإ", "Saba' (Sheba)", 428));
       surahList.add(new SurahModel(35, "فاطر", "Fatir (The Originator of Creation)", 435));
       surahList.add(new SurahModel(36, "يس", "Ya-Sin (Ya-Sin)", 441));
       surahList.add(new SurahModel(37, "الصافات", "As-Saffat (Those Ranged in Ranks)", 446));
       surahList.add(new SurahModel(38, "ص", "Sad (Sad)", 453));
       surahList.add(new SurahModel(39, "الزمر", "Az-Zumar (The Groups)", 459));
       surahList.add(new SurahModel(40, "غافر", "Ghafir (The Forgiver)", 468));
       surahList.add(new SurahModel(41, "فصلت", "Fussilat (They are explained in detail)", 477));
       surahList.add(new SurahModel(42, "الشورى", "Ash-Shura (The Consultation)", 483));
       surahList.add(new SurahModel(43, "الزخرف", "Az-Zukhruf (The Gold Adornments)", 490));
       surahList.add(new SurahModel(44, "الدخان", "Ad-Dukhan (The Smoke)", 496));
       surahList.add(new SurahModel(45, "الجاثية", "Al-Jathiyah (The Kneeling)", 499));
       surahList.add(new SurahModel(46, "الأحقاف", "Al-Ahqaf (The Curved Sand-hills)", 503));
       surahList.add(new SurahModel(47, "محمد", "Muhammad (Muhammad)", 507));
       surahList.add(new SurahModel(48, "الفتح", "Al-Fath (The Victory)", 511));
       surahList.add(new SurahModel(49, "الحجرات", "Al-Hujurat (The Dwellings)", 516));
       surahList.add(new SurahModel(50, "ق", "Qaf (Qaf)", 518));
       surahList.add(new SurahModel(51, "الذاريات", "Adh-Dhariyat (The Winds that Scatter)", 521));
       surahList.add(new SurahModel(52, "الطور", "At-Tur (The Mount)", 524));
       surahList.add(new SurahModel(53, "النجم", "An-Najm (The Star)", 526));
       surahList.add(new SurahModel(54, "القمر", "Al-Qamar (The Moon)", 529));
       surahList.add(new SurahModel(55, "الرحمن", "Ar-Rahman (The Most Gracious)", 532));
       surahList.add(new SurahModel(56, "الواقعة", "Al-Waqi'ah (The Event)", 535));
       surahList.add(new SurahModel(57, "الحديد", "Al-Hadid (The Iron)", 538));
       surahList.add(new SurahModel(58, "المجادلة", "Al-Mujadilah (The Woman who disputes)", 542));
       surahList.add(new SurahModel(59, "الحشر", "Al-Hashr (The Gathering)", 546));
       surahList.add(new SurahModel(60, "الممتحنة", "Al-Mumtahanah (The Woman to be examined)", 549));
       surahList.add(new SurahModel(61, "الصف", "As-Saff (The Row)", 552));
       surahList.add(new SurahModel(62, "الجمعة", "Adh-Dhariyat (The Winds that Scatter)", 553));
       surahList.add(new SurahModel(63, "المنافقون", "Al-Munafiqun (The Hypocrites)", 555));
       surahList.add(new SurahModel(64, "التغابن", "At-Taghabun (Mutual Loss and Gain)", 556));
       surahList.add(new SurahModel(65, "الطلاق", "At-Talaq (The Divorce)", 558));
       surahList.add(new SurahModel(66, "التحريم", "At-Tahrim (The Prohibition)", 560));
       surahList.add(new SurahModel(67, "الملك", "Al-Mulk (Dominion)", 562));
       surahList.add(new SurahModel(68, "القلم", "Al-Qalam (The Pen)", 565));
       surahList.add(new SurahModel(69, "الحاقة", "Al-Haqqah (The Inevitable)", 567));
       surahList.add(new SurahModel(70, "المعارج", "Al-Ma'arij (The Ways of Ascent)", 569));
       surahList.add(new SurahModel(71, "نوح", "Nuh (Noah)", 571));
       surahList.add(new SurahModel(72, "الجن", "Al-Jinn (The Jinn)", 572));
       surahList.add(new SurahModel(73, "المزمل", "Al-Muzammil (The One wrapped in Garments)", 574));
       surahList.add(new SurahModel(74, "المدثر", "Al-Muddaththir (The One Enveloped)", 576));
       surahList.add(new SurahModel(75, "القيامة", "Al-Qiyamah (The Resurrection)", 578));
       surahList.add(new SurahModel(76, "الانسان", "Al-Insan (Man)", 579));
       surahList.add(new SurahModel(77, "المرسلات", "Al-Mursalat (Those sent forth)", 581));
       surahList.add(new SurahModel(78, "النبإ", "An-Naba' (The Great News)", 582));
       surahList.add(new SurahModel(79, "النازعات", "An-Nazi'at (Those Who Pull Out)", 584));
       surahList.add(new SurahModel(80, "عبس", "'Abasa (He Frowned)", 585));
       surahList.add(new SurahModel(81, "التكوير", "At-Takwir (Winding Round And Losing Its Light)", 586));
       surahList.add(new SurahModel(82, "الإنفطار", "Al-Infitar (The Cleaving)", 587));
       surahList.add(new SurahModel(83, "المطففين", "Al-Mutaffifin (Those Who Deal In Fraud)", 588));
       surahList.add(new SurahModel(84, "الإنشقاق", "Al-Inshiqaq (The Splitting Asunder)", 588));
       surahList.add(new SurahModel(85, "البروج", "Al-Buruj (The Big Stars)", 590));
       surahList.add(new SurahModel(86, "الطارق", "At-Tariq (The Night Comer)", 591));
       surahList.add(new SurahModel(87, "الأعلى", "Al-A'la (The Most High)", 591));
       surahList.add(new SurahModel(88, "الغاشية", "Al-Ghashiyah (The Overwhelming)", 592));
       surahList.add(new SurahModel(89, "الفجر", "Al-Fajr (The Break of Day)", 593));
       surahList.add(new SurahModel(90, "البلد", "Al-Balad (The City)", 592));
       surahList.add(new SurahModel(91, "الشمس", "Ash-Shams (The Sun)", 595));
       surahList.add(new SurahModel(92, "الليل", "Al-Lail (The Night)", 1595));
       surahList.add(new SurahModel(93, "الضحى", "Ad-Duha (The Forenoon - After Sunrise)", 596));
       surahList.add(new SurahModel(94, "الشرح", "Ash-Sharh (The Opening Forth)", 596));
       surahList.add(new SurahModel(95, "التين", "At-Tin (The Fig)", 597));
       surahList.add(new SurahModel(96, "العلق", "Al-'Alaq (The Clot)", 597));
       surahList.add(new SurahModel(97, "القدر", "Al-Qadr (The Night of Decree)", 598));
       surahList.add(new SurahModel(98, "البينة", "Al-Baiyyinah (The Clear Evidence)", 59));
       surahList.add(new SurahModel(99, "الزلزلة", "Az-Zalzalah (The Earthquake)", 599));
       surahList.add(new SurahModel(100, "العاديات", "Al-'Adiyat (Those That Run)", 599));
       surahList.add(new SurahModel(101, "القارعة", "Al-Qari'ah (The Striking Hour)", 600));
       surahList.add(new SurahModel(102, "التكاثر", "At-Takathur (The Piling Up - The Emulous Desire)", 600));
       surahList.add(new SurahModel(103, "العصر", "Al-'Asr (The Time)", 601));
       surahList.add(new SurahModel(104, "الهمزة", "Al-Humazah (The Slanderer)", 601));
       surahList.add(new SurahModel(105, "الفيل", "Al-Fil (The Elephant)", 601));
       surahList.add(new SurahModel(106, "قريش", "Quraish (Quraish)", 602));
       surahList.add(new SurahModel(107, "الماعون", "Al-Ma'un (The Small Kindness)", 602));
       surahList.add(new SurahModel(108, "الكوثر", "Al-Kauthar (A River In Paradise)", 602));
       surahList.add(new SurahModel(109, "الكافرون", "Al-Kafirun (The Disbelievers)", 603));
       surahList.add(new SurahModel(110, "النصر", "An-Nasr (The Help)", 603));
       surahList.add(new SurahModel(111, "المسد", "Al-Masad (The Palm Fiber)", 603));
       surahList.add(new SurahModel(112, "الإخلاص", "Al-Ikhlas (The Purity)", 604));
       surahList.add(new SurahModel(113, "الفلق", "Al-Falaq (The Daybreak)", 604));
       surahList.add(new SurahModel(114, "الناس", "An-Nas (Mankind)", 604));

       return surahList;
    }


}
